# Generated by Django 5.0 on 2024-01-06 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bunnyquestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiontext', models.CharField(max_length=500)),
                ('dateofquest', models.DateTimeField(verbose_name='date published rabbit')),
            ],
        ),
        migrations.CreateModel(
            name='bunnychoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choicetext', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rabbitpolls.bunnyquestion')),
            ],
        ),
    ]
